#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""LogBERT training using processed TFRecord labels.

This script loads the TFRecord files generated by ``preprocessing.py`` and
fine‑tunes a BERT model for multi‑label classification of log lines. After
training, it extracts [CLS] embeddings for downstream tasks.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List, Dict

import numpy as np
import pandas as pd
import tensorflow as tf
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from transformers import BertForSequenceClassification, BertTokenizer
from torch.optim import AdamW
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PROCESSED_DIR = Path("processed")
OUTPUT_DIR = Path("embeddings")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MAX_SEQ_LENGTH = 128
BATCH_SIZE = 16
NUM_EPOCHS = 2
LEARNING_RATE = 2e-5

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def get_device() -> torch.device:
    """Return best available computation device."""
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def parse_tfrecord(example: tf.Tensor) -> Dict[str, tf.Tensor]:
    """Parse a serialized TFRecord example."""
    feature_description = {
        "l": tf.io.FixedLenFeature([], tf.string),
        "y": tf.io.FixedLenFeature([], tf.string),
    }
    return tf.io.parse_single_example(example, feature_description)


def load_tfrecords(directory: Path = PROCESSED_DIR) -> pd.DataFrame:
    """Load all TFRecord files into a DataFrame."""
    tfrecord_files = list(directory.glob("**/*.tfrecord"))
    if not tfrecord_files:
        raise FileNotFoundError(f"No TFRecord files found in {directory}")

    logs: List[str] = []
    labels: List[str] = []

    for path in tfrecord_files:
        dataset = tf.data.TFRecordDataset(str(path), compression_type="GZIP")
        for raw in dataset:
            parsed = parse_tfrecord(raw)
            logs.append(parsed["l"].numpy().decode("utf-8"))
            labels.append(parsed["y"].numpy().decode("utf-8"))

    return pd.DataFrame({"log": logs, "label_json": labels})


def collect_attack_types(df: pd.DataFrame) -> List[str]:
    """Return sorted list of all attack labels present in the data."""
    attack_set = set()
    for label_str in df["label_json"]:
        try:
            labels = json.loads(label_str)
            if not isinstance(labels, list):
                labels = [labels]
            attack_set.update([lbl for lbl in labels if lbl])
        except json.JSONDecodeError:
            continue
    return sorted(attack_set)


class LogDataset(Dataset):
    """Torch dataset for log lines and multi‑label targets."""

    def __init__(self, df: pd.DataFrame, tokenizer: BertTokenizer, label_to_idx: Dict[str, int]):
        self.texts = df["log"].tolist()
        self.labels = [self._encode_labels(j, label_to_idx) for j in df["label_json"]]
        self.tokenizer = tokenizer

    @staticmethod
    def _encode_labels(label_json: str, label_to_idx: Dict[str, int]) -> np.ndarray:
        vec = np.zeros(len(label_to_idx), dtype=np.float32)
        try:
            labels = json.loads(label_json)
            if not isinstance(labels, list):
                labels = [labels]
            for lbl in labels:
                if lbl in label_to_idx:
                    vec[label_to_idx[lbl]] = 1.0
        except json.JSONDecodeError:
            pass
        return vec

    def __len__(self) -> int:  # pragma: no cover - trivial
        return len(self.texts)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=MAX_SEQ_LENGTH,
            return_tensors="pt",
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.float)
        return item


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_model() -> None:
    device = get_device()
    print(f"Using device: {device}")

    df = load_tfrecords()
    attack_types = collect_attack_types(df)
    label_to_idx = {lbl: i for i, lbl in enumerate(attack_types)}

    tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    model = BertForSequenceClassification.from_pretrained(
        "bert-base-uncased",
        num_labels=len(attack_types),
        problem_type="multi_label_classification",
    ).to(device)

    train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)
    train_ds = LogDataset(train_df, tokenizer, label_to_idx)
    val_ds = LogDataset(val_df, tokenizer, label_to_idx)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE)

    optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

    for epoch in range(1, NUM_EPOCHS + 1):
        model.train()
        train_loss = 0.0
        for batch in tqdm(train_loader, desc=f"Epoch {epoch} Training"):
            batch = {k: v.to(device) for k, v in batch.items()}
            optimizer.zero_grad()
            outputs = model(**batch)
            loss = outputs.loss
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
        avg_train = train_loss / len(train_loader)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for batch in val_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                outputs = model(**batch)
                val_loss += outputs.loss.item()
        avg_val = val_loss / len(val_loader)
        print(f"Epoch {epoch}: train loss {avg_train:.4f} - val loss {avg_val:.4f}")

    # Save the fine tuned model
    model.save_pretrained(OUTPUT_DIR / "logbert_model")
    tokenizer.save_pretrained(OUTPUT_DIR / "logbert_model")

    # -----------------------------------------------------------------------
    # Extract embeddings for all data
    # -----------------------------------------------------------------------
    full_ds = LogDataset(df, tokenizer, label_to_idx)
    full_loader = DataLoader(full_ds, batch_size=BATCH_SIZE)

    model.eval()
    embeddings = []
    with torch.no_grad():
        for batch in tqdm(full_loader, desc="Extracting embeddings"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            outputs = model.bert(input_ids=input_ids, attention_mask=attention_mask)
            cls_emb = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            embeddings.append(cls_emb)

    embeddings_array = np.concatenate(embeddings, axis=0)
    sequence_ids = np.arange(len(embeddings_array))

    np.savez_compressed(
        OUTPUT_DIR / "logbert_embeddings.npz",
        embeddings=embeddings_array,
        sequence_ids=sequence_ids,
    )

    with open(OUTPUT_DIR / "logbert_labels.json", "w", encoding="utf-8") as f:
        json.dump(attack_types, f, indent=2)

    print(f"Saved embeddings to {OUTPUT_DIR / 'logbert_embeddings.npz'}")


if __name__ == "__main__":
    train_model()
