#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
XGBoost Multi-Label Model for Log Anomaly Detection - Optimized
------------------------------------------------------
Uses a One-vs-Rest (OvR) strategy with XGBoost to predict multi-label
binary vectors (e.g., [0, 1, 0, 0, 1]) indicating active attack types.
Processes each log type separately for optimal performance.
"""

import os
import pickle
import argparse
import time
import numpy as np
import pandas as pd
from pathlib import Path
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, precision_score, recall_score, multilabel_confusion_matrix, hamming_loss
import joblib
import json
import multiprocessing
from functools import partial
from tqdm import tqdm
from halo import Halo

# --- Project Paths & Configuration ---
ROOT = Path(__file__).resolve().parent.parent

EMBEDDINGS_DIR = ROOT / 'embeddings'
MODELS_BASE_DIR = ROOT / 'models' / 'xgboost_ml' 
RESULTS_BASE_DIR = ROOT / 'results' / 'xgboost_ml'

for dir_path in [MODELS_BASE_DIR, RESULTS_BASE_DIR]:
    dir_path.mkdir(parents=True, exist_ok=True)

# For optimization: tune thread counts
CPU_COUNT = os.cpu_count()
N_JOBS = max(1, CPU_COUNT - 1) if CPU_COUNT else -1

def find_available_log_types():
    """Find available log types in the embeddings directory."""
    if not EMBEDDINGS_DIR.exists():
        return []
    
    available_types = []
    # Check for specific log type directories with embeddings
    for path in EMBEDDINGS_DIR.iterdir():
        if path.is_dir() and (path / "embeddings.pkl").exists() and (path / "labels.pkl").exists():
            available_types.append(path.name)
    
    return sorted(available_types)

def read_key_file(key_file_path):
    """Read attack type mapping from a key file generated by FastText embedding"""
    attack_types = []
    
    if not key_file_path.exists():
        print(f"Warning: Key file not found at {key_file_path}")
        return []
        
    try:
        with open(key_file_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split(',')
                    if len(parts) >= 2:
                        index, attack_type = int(parts[0]), parts[1]
                        # Ensure the list has enough slots
                        while len(attack_types) <= index:
                            attack_types.append(None)
                        attack_types[index] = attack_type
    except Exception as e:
        print(f"Error reading key file: {e}")
        return []
        
    return attack_types

def load_data(embeddings_file_x, labels_file_y, context, key_file=None, test_size=0.2, random_state=42):
    """
    Loads embeddings and multi-label binary indicators with optimized memory usage.
    Dynamically determines label names from key file if available.
    """
    print(f"Loading embeddings from: {embeddings_file_x}")
    print(f"Loading multi-label binary indicators from: {labels_file_y}")

    try:
        # Use mmap_mode for large files to reduce memory usage
        with open(embeddings_file_x, 'rb') as f:
            X = pickle.load(f)
        with open(labels_file_y, 'rb') as f:
            Y_multi = pickle.load(f)
    except FileNotFoundError as e:
        print(f"Error loading data: {e}")
        print(f"Please ensure the specified embedding and label files exist.")
        raise

    # Convert to appropriate numpy arrays with optimal data types
    if not isinstance(X, np.ndarray):
        X = np.array(X, dtype=np.float32)  # Use float32 instead of float64 to save memory
    elif X.dtype == np.float64:
        X = X.astype(np.float32)
    
    if not isinstance(Y_multi, np.ndarray):
        Y_multi = np.array(Y_multi, dtype=np.int8)  # Use int8 for binary labels
    elif Y_multi.dtype != np.int8:
        Y_multi = Y_multi.astype(np.int8)

    # Handle 1D arrays (convert to 2D if possible)
    if Y_multi.ndim == 1: 
        print("Warning: Y_multi loaded as 1D array. Attempting to stack into 2D if it contains lists/arrays.")
        try:
            Y_multi = np.array([np.array(row, dtype=np.int8) for row in Y_multi])
            if Y_multi.ndim == 1: 
                raise ValueError("Y_multi could not be converted to a 2D array of labels.")
        except Exception as stack_e:
            print(f"Error converting Y_multi to 2D: {stack_e}")
            raise ValueError(f"Loaded Y_multi (shape {Y_multi.shape}) is not a 2D numpy array of label vectors.")
    
    if Y_multi.ndim != 2:
         raise ValueError(f"Loaded Y_multi (shape {Y_multi.shape}) is not a 2D numpy array as expected for multi-label tasks.")
    
    # Determine attack type names
    num_labels = Y_multi.shape[1]
    attack_types = None
    
    # Try to read from key file first
    if key_file and Path(key_file).exists():
        attack_types = read_key_file(Path(key_file))
        if len(attack_types) != num_labels:
            print(f"Warning: Number of labels in key file ({len(attack_types)}) does not match label matrix dimensions ({num_labels})")
    
    # If no attack types from key file, generate generic names
    if not attack_types or len(attack_types) == 0:
        print(f"No attack type names found in key file, using generic names")
        attack_types = [f"attack_type_{i}" for i in range(num_labels)]
    
    print(f"Loaded X shape: {X.shape}")
    print(f"Loaded Y_multi shape: {Y_multi.shape}")
    print(f"Attack types for {context}: {attack_types}")
    
    # Calculate overall attack statistics efficiently
    attack_samples = np.sum(Y_multi, axis=0)
    total_samples = Y_multi.shape[0]
    print("\nAttack type distribution in dataset:")
    for i, attack_type in enumerate(attack_types):
        count = attack_samples[i]
        percentage = (count / total_samples) * 100
        print(f"  {attack_type}: {count} occurrences ({percentage:.2f}%)")
    
    # Calculate total logs with at least one attack (vectorized operation)
    logs_with_attacks = np.sum(np.any(Y_multi == 1, axis=1))
    attack_percentage = (logs_with_attacks / total_samples) * 100
    print(f"\nLogs with at least one attack: {logs_with_attacks} ({attack_percentage:.2f}%)")
    print(f"Normal logs: {total_samples - logs_with_attacks} ({100 - attack_percentage:.2f}%)")

    # Create stratified train/test split
    X_train, X_test, Y_train_multi, Y_test_multi = train_test_split(
        X, Y_multi, test_size=test_size, random_state=random_state, 
        stratify=Y_multi.sum(axis=1) > 0 if Y_multi.shape[0] > 1 and Y_multi.shape[1] > 0 else None 
    )
    print(f"X_train shape: {X_train.shape}, Y_train_multi shape: {Y_train_multi.shape}")
    print(f"X_test shape: {X_test.shape}, Y_test_multi shape: {Y_test_multi.shape}")
    
    return X_train, X_test, Y_train_multi, Y_test_multi, attack_types

def train_single_model(params):
    """Train a single XGBoost model - for parallel processing"""
    idx, attack_type, X_train, y_label, n_jobs, class_weight = params
    
    # Check for sufficient samples of both classes
    unique_classes, class_counts = np.unique(y_label, return_counts=True)
    if len(unique_classes) < 2 or np.min(class_counts) < 10:  # Need sufficient samples of each class
        print(f"    Skipping training for '{attack_type}' - insufficient samples (class counts: {class_counts})")
        return idx, None, 0
    
    # Print class distribution for this label
    pos_count = np.sum(y_label == 1)
    neg_count = np.sum(y_label == 0)
    pos_percent = (pos_count / len(y_label)) * 100
    print(f"    Class distribution: Positive: {pos_count} ({pos_percent:.2f}%), Negative: {neg_count} ({100-pos_percent:.2f}%)")
    
    # Calculate class weights if needed
    scale_pos_weight = 1.0
    if class_weight and pos_count > 0 and neg_count > 0:
        # Calculate appropriate class weight for imbalance
        scale_pos_weight = neg_count / pos_count
    
    model_start_time = time.time()
    
    # Define optimal hyperparameters for this specific attack type
    try:
        model = XGBClassifier(
            n_estimators=100, 
            max_depth=6,         
            learning_rate=0.1,
            gamma=0.1,
            subsample=0.8,       
            colsample_bytree=0.8, 
            min_child_weight=3,   # Added to prevent overfitting
            scale_pos_weight=scale_pos_weight,  # Balance classes
            random_state=42,
            n_jobs=n_jobs,
            tree_method='hist',  
            use_label_encoder=False,
            verbosity=0,
            importance_type='gain'
        )
        
        model.fit(X_train, y_label)
    except Exception as e:
        print(f"    Error training model: {e}. Trying with simpler parameters.")
        # Fallback to simpler model if error occurs
        model = XGBClassifier(
            n_estimators=50,
            max_depth=4,
            learning_rate=0.1,
            random_state=42,
            n_jobs=n_jobs,
            use_label_encoder=False,
            verbosity=0
        )
        model.fit(X_train, y_label)
    
    training_time = time.time() - model_start_time
    print(f"    Model for '{attack_type}' trained in {training_time:.2f}s.")
    
    return idx, model, training_time

def train_evaluate_ovr_xgboost(X_train, Y_train_multi, X_test, Y_test_multi, attack_types, results_dir, models_dir,
                              use_parallel=True, early_stopping=True, feature_fraction=0.8, class_weight=True):
    """
    Trains one XGBoost binary classifier per attack type using One-vs-Rest strategy.
    Optimized for speed and memory usage.
    """
    num_labels = len(attack_types)
    
    # Feature selection if requested
    if feature_fraction < 1.0 and feature_fraction > 0:
        num_features = X_train.shape[1]
        num_features_to_keep = max(1, int(num_features * feature_fraction))
        print(f"Performing feature selection: keeping {num_features_to_keep} of {num_features} features")
        
        # Train a quick XGBoost model to get feature importances
        feature_selector = XGBClassifier(
            n_estimators=50, 
            max_depth=5,
            learning_rate=0.1,
            n_jobs=N_JOBS,
            tree_method='hist',
            random_state=42
        )
        
        # Use sum of labels as target for feature selection
        any_attack = np.any(Y_train_multi == 1, axis=1).astype(np.int8)
        feature_selector.fit(X_train, any_attack)
        
        # Get feature importances and select top features
        importances = feature_selector.feature_importances_
        top_indices = np.argsort(importances)[-num_features_to_keep:]
        
        # Select only these features
        X_train = X_train[:, top_indices]
        X_test = X_test[:, top_indices]
        print(f"Feature selection complete: X_train shape now {X_train.shape}")
    
    print(f"\nStarting One-vs-Rest XGBoost training for {num_labels} attack types...")
    
    if use_parallel and num_labels > 1:
        # Prepare parameters for parallel processing
        jobs_per_model = max(1, N_JOBS // min(num_labels, multiprocessing.cpu_count()))
        params_list = [
            (i, attack_types[i], X_train, Y_train_multi[:, i], jobs_per_model, class_weight) 
            for i in range(num_labels)
        ]
        
        # Train models in parallel
        print(f"Training {num_labels} models in parallel with {jobs_per_model} threads per model")
        trained_models = [None] * num_labels
        training_times = [0] * num_labels
        skipped_indices = []
        
        with multiprocessing.Pool(min(num_labels, multiprocessing.cpu_count())) as pool:
            results = list(tqdm(pool.imap(train_single_model, params_list), 
                               total=len(params_list), 
                               desc="Training models", 
                               ascii=True))
            
            # Collect results
            for idx, model, training_time in results:
                trained_models[idx] = model
                training_times[idx] = training_time
                if model is None:
                    skipped_indices.append(idx)
    else:
        # Sequential training
        trained_models = []
        training_times = []
        skipped_indices = []

        for i in range(num_labels):
            attack_type = attack_types[i]
            print(f"  Training model {i+1}/{num_labels} for attack type: '{attack_type}'...")
            
            y_train_single_label = Y_train_multi[:, i]

            # Check for sufficient samples of both classes
            unique_classes, class_counts = np.unique(y_train_single_label, return_counts=True)
            if len(unique_classes) < 2 or np.min(class_counts) < 10:  # Need sufficient samples of each class
                print(f"    Skipping training for '{attack_type}' - insufficient samples (class counts: {class_counts})")
                trained_models.append(None) 
                training_times.append(0)
                skipped_indices.append(i)
                continue
            
            # Calculate class weights if needed
            scale_pos_weight = 1.0
            if class_weight:
                pos_count = np.sum(y_train_single_label == 1)
                neg_count = np.sum(y_train_single_label == 0)
                if pos_count > 0 and neg_count > 0:
                    scale_pos_weight = neg_count / pos_count
            
            model_start_time = time.time()
            model = XGBClassifier(
                n_estimators=100, 
                max_depth=6,  
                learning_rate=0.1,
                gamma=0.1,
                subsample=0.8,  
                colsample_bytree=0.8,  
                min_child_weight=3,
                scale_pos_weight=scale_pos_weight,
                random_state=42,
                n_jobs=N_JOBS,
                tree_method='hist',  
                use_label_encoder=False, 
                verbosity=0
            )
            
            # Print class distribution for this label
            pos_count = np.sum(y_train_single_label == 1)
            neg_count = np.sum(y_train_single_label == 0)
            pos_percent = (pos_count / len(y_train_single_label)) * 100
            print(f"    Class distribution: Positive: {pos_count} ({pos_percent:.2f}%), Negative: {neg_count} ({100-pos_percent:.2f}%)")
            
            # Use early stopping if requested and we have enough data
            if early_stopping and len(X_train) > 1000:
                # Create a validation set
                val_size = min(0.2, 1000/len(X_train))
                X_train_split, X_val, y_train_split, y_val = train_test_split(
                    X_train, y_train_single_label, test_size=val_size, random_state=42,
                    stratify=y_train_single_label
                )
                
                model.fit(
                    X_train_split, y_train_split,
                    eval_set=[(X_val, y_val)],
                    early_stopping_rounds=10,
                    eval_metric='logloss',
                    verbose=False
                )
            else:
                model.fit(X_train, y_train_single_label)
                
            current_training_time = time.time() - model_start_time
            training_times.append(current_training_time)
            trained_models.append(model)
            print(f"    Model for '{attack_type}' trained in {current_training_time:.2f}s.")

    total_training_time = sum(training_times)
    print(f"Total training time for all OvR models: {total_training_time:.2f}s")

    # Save models and metadata
    models_save_path = models_dir / "ovr_xgboost_models.joblib"
    metadata_path = models_dir / "model_metadata.json"
    
    # Compress the models when saving
    joblib.dump(trained_models, models_save_path, compress=3)
    
    # Save metadata (attack types, skipped models, etc.)
    metadata = {
        "attack_types": attack_types,
        "skipped_indices": skipped_indices,
        "training_times": training_times,
        "total_training_time": total_training_time,
        "feature_fraction": feature_fraction
    }
    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=4)
        
    print(f"Saved all OvR XGBoost models to: {models_save_path}")
    print(f"Saved model metadata to: {metadata_path}")

    print("\nPredicting on the test set...")
    # Use int8 for binary predictions to save memory
    Y_pred_multi = np.zeros_like(Y_test_multi, dtype=np.int8)

    # Make predictions in batches to reduce memory usage for large test sets
    batch_size = 10000
    num_batches = max(1, len(X_test) // batch_size + (1 if len(X_test) % batch_size > 0 else 0))
    
    # Store individual metrics for each model
    model_metrics = []
    
    for i in tqdm(range(num_labels), desc="Making predictions", ascii=True):
        model = trained_models[i]
        if model is not None:
            # Make batch predictions
            if len(X_test) > batch_size:
                y_preds = []
                for b in range(num_batches):
                    start_idx = b * batch_size
                    end_idx = min((b + 1) * batch_size, len(X_test))
                    y_preds.append(model.predict(X_test[start_idx:end_idx]))
                Y_pred_multi[:, i] = np.concatenate(y_preds)
            else:
                Y_pred_multi[:, i] = model.predict(X_test)
            
            # Calculate per-model metrics for better understanding
            true_positives = np.sum((Y_test_multi[:, i] == 1) & (Y_pred_multi[:, i] == 1))
            false_positives = np.sum((Y_test_multi[:, i] == 0) & (Y_pred_multi[:, i] == 1))
            false_negatives = np.sum((Y_test_multi[:, i] == 1) & (Y_pred_multi[:, i] == 0))
            true_negatives = np.sum((Y_test_multi[:, i] == 0) & (Y_pred_multi[:, i] == 0))
            
            precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
            recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
            f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
            accuracy = (true_positives + true_negatives) / len(Y_test_multi)
            
            model_metrics.append({
                'attack_type': attack_types[i],
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1': f1,
                'true_positives': int(true_positives),
                'false_positives': int(false_positives),
                'false_negatives': int(false_negatives),
                'true_negatives': int(true_negatives)
            })
            
            print(f"  Model for '{attack_types[i]}':")
            print(f"    Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1: {f1:.4f}")
            print(f"    TP: {true_positives}, FP: {false_positives}, FN: {false_negatives}, TN: {true_negatives}")
        else: 
            print(f"  Model for '{attack_types[i]}' was skipped, predicting 0 for all samples")
            Y_pred_multi[:, i] = 0  # Predict 0 if model was skipped

    print("\nEvaluating multi-label predictions...")
    report_path = results_dir / "classification_report.txt"
    metrics_summary_path = results_dir / "metrics_summary.json"
    confusion_matrices_path = results_dir / "confusion_matrices.txt"

    # Calculate overall metrics
    f1_micro = f1_score(Y_test_multi, Y_pred_multi, average='micro', zero_division=0)
    f1_macro = f1_score(Y_test_multi, Y_pred_multi, average='macro', zero_division=0)
    f1_samples = f1_score(Y_test_multi, Y_pred_multi, average='samples', zero_division=0)
    precision_micro = precision_score(Y_test_multi, Y_pred_multi, average='micro', zero_division=0)
    recall_micro = recall_score(Y_test_multi, Y_pred_multi, average='micro', zero_division=0)
    hamming = hamming_loss(Y_test_multi, Y_pred_multi)

    print(f"  F1 Score (Micro): {f1_micro:.4f}")
    print(f"  F1 Score (Macro): {f1_macro:.4f}")
    print(f"  F1 Score (Samples): {f1_samples:.4f}")
    print(f"  Precision (Micro): {precision_micro:.4f}")
    print(f"  Recall (Micro): {recall_micro:.4f}")
    print(f"  Hamming Loss: {hamming:.4f}")
    
    # Generate per-label metrics
    report = classification_report(Y_test_multi, Y_pred_multi, target_names=attack_types, zero_division=0)
    print("\nPer-Label Classification Report:")
    print(report)
    
    # Generate confusion matrices
    multi_label_matrices = multilabel_confusion_matrix(Y_test_multi, Y_pred_multi)
    
    with open(confusion_matrices_path, 'w') as f:
        f.write("Multi-Label Confusion Matrices\n")
        f.write("===========================\n\n")
        
        for i, attack_type in enumerate(attack_types):
            cm = multi_label_matrices[i]
            f.write(f"Attack Type: {attack_type}\n")
            f.write("TN | FP\n")
            f.write("---|---\n")
            f.write("FN | TP\n\n")
            f.write(f"{cm[0][0]} | {cm[0][1]}\n")
            f.write(f"{cm[1][0]} | {cm[1][1]}\n\n")
            
            # Calculate metrics from confusion matrix
            tn, fp = cm[0]
            fn, tp = cm[1]
            total = tn + fp + fn + tp
            accuracy = (tn + tp) / total if total > 0 else 0
            
            f.write(f"Accuracy: {accuracy:.4f}\n")
            f.write(f"True Positives: {tp}, False Positives: {fp}\n")
            f.write(f"True Negatives: {tn}, False Negatives: {fn}\n")
            f.write("="*30 + "\n\n")

    # Save classification report
    context_name_for_report = results_dir.name.replace(f"run_{results_dir.parent.name}_", "").split('_')[0] \
                              if "run_" in results_dir.name else results_dir.name

    with open(report_path, 'w') as f:
        f.write(f"XGBoost Multi-Label (One-vs-Rest) Classification Report\n")
        f.write(f"Context: {context_name_for_report}\n")
        f.write("="*60 + "\n")
        f.write(f"Total training time: {total_training_time:.2f}s\n\n")
        f.write(f"Overall Metrics:\n")
        f.write(f"  F1 Score (Micro): {f1_micro:.4f}\n")
        f.write(f"  F1 Score (Macro): {f1_macro:.4f}\n")
        f.write(f"  F1 Score (Samples): {f1_samples:.4f}\n")
        f.write(f"  Precision (Micro): {precision_micro:.4f}\n")
        f.write(f"  Recall (Micro): {recall_micro:.4f}\n")
        f.write(f"  Hamming Loss: {hamming:.4f}\n\n")
        f.write("Per-Label Classification Report:\n")
        f.write(report)
        
        # Add class distribution information
        f.write("\nClass Distribution in Training Data:\n")
        train_pos_counts = np.sum(Y_train_multi, axis=0)
        for i, attack_type in enumerate(attack_types):
            pos_count = train_pos_counts[i]
            percent = (pos_count / len(Y_train_multi)) * 100
            f.write(f"  {attack_type}: {pos_count} positive samples ({percent:.2f}%)\n")

    # Save metrics summary
    metrics_summary = {
        'context': context_name_for_report,
        'total_training_time_seconds': total_training_time,
        'f1_micro': f1_micro, 
        'f1_macro': f1_macro, 
        'f1_samples': f1_samples,
        'precision_micro': precision_micro,
        'recall_micro': recall_micro,
        'hamming_loss': hamming,
        'per_label_metrics': {m['attack_type']: {
            k: v for k, v in m.items() if k != 'attack_type'
        } for m in model_metrics}
    }
    
    with open(metrics_summary_path, 'w') as f:
        json.dump(metrics_summary, f, indent=4)
    
    print(f"\nFull classification report saved to: {report_path}")
    print(f"Confusion matrices saved to: {confusion_matrices_path}")
    print(f"Metrics summary saved to: {metrics_summary_path}")
    
    return metrics_summary

def process_log_type(log_type, feature_fraction=0.8, test_size=0.2, random_state=42):
    """Process a single log type with XGBoost."""
    print(f"\n{'='*80}\nProcessing log type: {log_type}\n{'='*80}")
    
    try:
        # Set paths based on log type
        if log_type == 'all_combined':
            embeddings_file_x_path = EMBEDDINGS_DIR / "embeddings_all_combined.pkl"
            labels_file_y_path = EMBEDDINGS_DIR / "labels_all_combined.pkl"
            key_file_path = EMBEDDINGS_DIR / "key_all_combined.txt"
        else:
            # Assume log_type is a directory name in embeddings/
            embeddings_file_x_path = EMBEDDINGS_DIR / log_type / "embeddings.pkl"
            labels_file_y_path = EMBEDDINGS_DIR / log_type / "labels.pkl"
            key_file_path = EMBEDDINGS_DIR / log_type / "key.txt"

        # Check if required files exist
        if not embeddings_file_x_path.exists() or not labels_file_y_path.exists():
            print(f"Error: Required input files not found for log type '{log_type}'.")
            print(f"  Expected X: {embeddings_file_x_path}")
            print(f"  Expected Y: {labels_file_y_path}")
            return None
            
        # Load data with dynamic label identification
        X_train, X_test, Y_train_multi, Y_test_multi, attack_types = load_data(
            embeddings_file_x_path, labels_file_y_path, log_type,
            key_file_path, test_size, random_state
        )

        # Set up directories for this run
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        run_context_name = log_type.replace('/', '_') 
        current_run_results_dir = RESULTS_BASE_DIR / f"run_{run_context_name}_{timestamp}"
        current_run_models_dir = MODELS_BASE_DIR / f"run_{run_context_name}_{timestamp}"
        current_run_results_dir.mkdir(parents=True, exist_ok=True)
        current_run_models_dir.mkdir(parents=True, exist_ok=True)

        # Train and evaluate with optimized parameters
        metrics = train_evaluate_ovr_xgboost(
            X_train, Y_train_multi, X_test, Y_test_multi,
            attack_types,
            current_run_results_dir,
            current_run_models_dir,
            use_parallel=True,
            early_stopping=True,
            feature_fraction=feature_fraction,
            class_weight=True
        )
        
        return metrics
        
    except Exception as e:
        print(f"Error processing log type {log_type}: {e}")
        import traceback
        traceback.print_exc()
        return None

def main():
    parser = argparse.ArgumentParser(description="XGBoost Multi-Label Model for Log Anomaly Detection.")
    parser.add_argument(
        '--log-type', type=str, default=None,
        help="Process a specific log type. If not provided, processes all available log types."
    )
    parser.add_argument(
        '--test_size', type=float, default=0.2,
        help="Proportion of the dataset to include in the test split."
    )
    parser.add_argument(
        '--random_state', type=int, default=42,
        help="Random state for reproducibility."
    )
    parser.add_argument(
        '--feature_fraction', type=float, default=0.8,
        help="Fraction of features to use (0.0-1.0). Default: 0.8"
    )
    args = parser.parse_args()

    overall_start_time = time.time()
    
    # Find available log types
    available_log_types = find_available_log_types()
    if not available_log_types:
        print("No log types with embeddings found. Please run fasttext_embedding.py first.")
        return
    
    print(f"Found {len(available_log_types)} log types: {', '.join(available_log_types)}")
    
    # Process either a specific log type or all available log types
    all_metrics = {}
    
    if args.log_type:
        # Process only the specified log type
        if args.log_type not in available_log_types and args.log_type != 'all_combined':
            print(f"Error: Log type '{args.log_type}' not found. Available types: {', '.join(available_log_types)}")
            return
            
        print(f"Processing log type: {args.log_type}")
        metrics = process_log_type(args.log_type, args.feature_fraction, args.test_size, args.random_state)
        if metrics:
            all_metrics[args.log_type] = metrics
    else:
        # Process all log types separately for best performance
        for log_type in tqdm(available_log_types, desc="Processing log types", ascii=True):
            print(f"\nProcessing log type: {log_type}")
            metrics = process_log_type(log_type, args.feature_fraction, args.test_size, args.random_state)
            if metrics:
                all_metrics[log_type] = metrics
    
    # Generate summary report if multiple log types were processed
    if len(all_metrics) > 1:
        summary_path = RESULTS_BASE_DIR / f"summary_{time.strftime('%Y%m%d-%H%M%S')}.txt"
        with open(summary_path, 'w') as f:
            f.write("XGBoost Multi-Label Models Summary\n")
            f.write("===============================\n\n")
            
            # Table header
            f.write(f"{'Log Type':<20} {'F1 Micro':<10} {'F1 Macro':<10} {'Precision':<10} {'Recall':<10}\n")
            f.write("-" * 65 + "\n")
            
            # Table rows
            for log_type, metrics in all_metrics.items():
                f1_micro = metrics.get('f1_micro', 0)
                f1_macro = metrics.get('f1_macro', 0)
                precision = metrics.get('precision_micro', 0)
                recall = metrics.get('recall_micro', 0)
                
                f.write(f"{log_type:<20} {f1_micro:<10.4f} {f1_macro:<10.4f} {precision:<10.4f} {recall:<10.4f}\n")
            
            # Add detailed F1 scores for each class
            f.write("\n\nDetailed Per-Class F1 Scores:\n")
            f.write("============================\n\n")
            
            for log_type, metrics in all_metrics.items():
                f.write(f"Log Type: {log_type}\n")
                f.write("-" * len(f"Log Type: {log_type}") + "\n")
                
                per_label_metrics = metrics.get('per_label_metrics', {})
                for attack_type, attack_metrics in per_label_metrics.items():
                    f1 = attack_metrics.get('f1', 0)
                    tp = attack_metrics.get('true_positives', 0)
                    fp = attack_metrics.get('false_positives', 0)
                    fn = attack_metrics.get('false_negatives', 0)
                    
                    f.write(f"  {attack_type:<30}: F1={f1:.4f} (TP={tp}, FP={fp}, FN={fn})\n")
                f.write("\n")
                
        print(f"\nSummary report with F1 scores saved to: {summary_path}")

    overall_end_time = time.time()
    print(f"\nTotal script execution time: {overall_end_time - overall_start_time:.2f} seconds.")
    print(f"Results and models saved in subdirectories under: {RESULTS_BASE_DIR} and {MODELS_BASE_DIR}")

if __name__ == '__main__':
    main() 